"""Tests for `homeframe.wall_corner_points`/`nearest_wall_corner_mm`
(docs/40 §5.B "snap-on-wall" — the click-noise fix for calibrating a foreign
floorplan against the home frame). Expected corner coordinates below are
hand-derived from the mask layout in each test's comment, not generated by
the code under test.
"""

from __future__ import annotations

import numpy as np
import pytest

from custom_components.anyvac import homeframe as hf


def _mask_from_rows(rows: list[str]) -> np.ndarray:
    """Build a bool mask from a list of equal-length strings, '#' = True."""
    return np.array([[c == "#" for c in row] for row in rows], dtype=bool)


def _pts(arr: np.ndarray) -> set[tuple[float, float]]:
    return {(float(x), float(y)) for x, y in arr.tolist()}


def test_empty_mask_has_no_corners() -> None:
    mask = np.zeros((5, 5), dtype=bool)
    corners = hf.wall_corner_points(mask)
    assert corners.shape == (0, 2)


def test_single_cell_has_its_4_convex_corners() -> None:
    # A lone wall cell at (row=2, col=3) -> vertices (3,2) (4,2) (3,3) (4,3).
    mask = np.zeros((5, 5), dtype=bool)
    mask[2, 3] = True
    corners = hf.wall_corner_points(mask)
    assert _pts(corners) == {(3, 2), (4, 2), (3, 3), (4, 3)}


def test_solid_rectangle_has_only_its_4_outer_corners() -> None:
    # 2x2 solid block at rows 1-2, cols 1-2 -> every interior/edge-straight
    # vertex has count in {0, 2-adjacent, 4} and is excluded; only the 4
    # true right-angle corners remain: (1,1) (3,1) (1,3) (3,3).
    mask = np.zeros((5, 5), dtype=bool)
    mask[1:3, 1:3] = True
    corners = hf.wall_corner_points(mask)
    assert _pts(corners) == {(1, 1), (3, 1), (1, 3), (3, 3)}


def test_l_shape_has_6_corners_5_convex_1_concave() -> None:
    # L-shape: row0 = cols 0-1, row1 = cols 0-2 (a 2-row L).
    #   ##.
    #   ###
    # Cells: (0,0) (0,1) (1,0) (1,1) (1,2).
    mask = _mask_from_rows([
        "##.",
        "###",
    ])
    corners = hf.wall_corner_points(mask)
    # Hand-traced right-angle vertices of that L's outline (crack coords):
    # (0,0) (2,0) [top of the notch] (2,1) [inner concave corner]
    # (3,1) (3,2) (0,2) — 6 vertices, the outline's own actual corners.
    assert _pts(corners) == {(0, 0), (2, 0), (2, 1), (3, 1), (3, 2), (0, 2)}


def test_diagonal_touch_is_a_bowtie_corner_not_a_straight_run() -> None:
    # Two cells touching only at one corner:
    #   #.
    #   .#
    mask = _mask_from_rows([
        "#.",
        ".#",
    ])
    corners = hf.wall_corner_points(mask)
    # The shared vertex (1,1) is a bowtie (count==2, diagonal) -> a corner.
    # Every other vertex around each 1x1 cell is a plain convex corner.
    assert (1.0, 1.0) in _pts(corners)
    # Each lone cell contributes 4 convex corners, one of which is the shared
    # bowtie vertex counted once -> 4 + 4 - 1 = 7 distinct vertices total.
    assert corners.shape[0] == 7


def test_straight_run_has_no_corners_along_its_length() -> None:
    # A straight horizontal 1-wide, 5-long wall: only its 4 end corners are
    # corners; every vertex along the top/bottom edge in between is a
    # straight (adjacent-pair) run, not a corner.
    mask = np.zeros((3, 7), dtype=bool)
    mask[1, 1:6] = True
    corners = hf.wall_corner_points(mask)
    assert _pts(corners) == {(1, 1), (6, 1), (1, 2), (6, 2)}


# ── nearest_wall_corner_mm ─────────────────────────────────────────────────


def _frame(mask: np.ndarray, *, cell_mm: float = 50, origin_mm: tuple[float, float] = (0.0, 0.0)) -> dict:
    return {"wall_mask": mask, "cell_mm": cell_mm, "origin_mm": origin_mm}


def test_nearest_wall_corner_snaps_to_closest_of_several() -> None:
    # Two separate single-cell walls: one at (row=0,col=0) -> corners at
    # (0,0)(1,0)(0,1)(1,1); one at (row=0,col=9) -> corners at
    # (9,0)(10,0)(9,1)(10,1). A query point near the first cluster (cell
    # units ~ (1.2, 0.8) -> mm (60, 40) at cell_mm=50) must snap to (1,1),
    # not anything from the far cluster.
    mask = np.zeros((5, 12), dtype=bool)
    mask[0, 0] = True
    mask[0, 9] = True
    frame = _frame(mask)
    got = hf.nearest_wall_corner_mm(frame, x_mm=60.0, y_mm=40.0)
    assert got == pytest.approx((50.0, 50.0))


def test_nearest_wall_corner_honours_frame_origin() -> None:
    # Same single-cell wall, but the frame's origin_mm is offset — the
    # returned point must be in absolute frame mm, not cell-relative.
    mask = np.zeros((3, 3), dtype=bool)
    mask[1, 1] = True  # corners at (1,1)(2,1)(1,2)(2,2) in cell units
    frame = _frame(mask, cell_mm=50, origin_mm=(1000.0, 2000.0))
    got = hf.nearest_wall_corner_mm(frame, x_mm=1000.0 + 1 * 50, y_mm=2000.0 + 1 * 50)
    assert got == pytest.approx((1000.0 + 50.0, 2000.0 + 50.0))


def test_nearest_wall_corner_returns_none_for_wall_free_frame() -> None:
    mask = np.zeros((10, 10), dtype=bool)
    frame = _frame(mask)
    assert hf.nearest_wall_corner_mm(frame, x_mm=100.0, y_mm=100.0) is None


def test_nearest_wall_corner_respects_custom_cell_mm() -> None:
    mask = np.zeros((3, 3), dtype=bool)
    mask[1, 1] = True  # corner at cell (2,2) is closest to a query near there
    frame = _frame(mask, cell_mm=25, origin_mm=(0.0, 0.0))
    got = hf.nearest_wall_corner_mm(frame, x_mm=2 * 25 + 2, y_mm=2 * 25 - 1)
    assert got == pytest.approx((50.0, 50.0))


# ── services._snap_wall_corner (docs/40 §5.B, home-px <-> mm shuttle) ──────


def test_snap_wall_corner_converts_px_snaps_and_converts_back() -> None:
    from custom_components.anyvac.services import _snap_wall_corner

    # Single wall cell at (row=0, col=0) -> nearest corner (in cell units)
    # to a click near it is (1,1) = mm (50,50) at cell_mm=50.
    mask = np.zeros((5, 5), dtype=bool)
    mask[0, 0] = True
    frame = {"wall_mask": mask, "cell_mm": 50, "scale": 4, "origin_mm": (0.0, 0.0)}
    # Click at home px (5, 5) -> mm (5/4*50, 5/4*50) = (62.5, 62.5), nearer
    # to corner mm (50, 50) than to (0, 0)/(50, 0)/(0, 50).
    result = _snap_wall_corner("f1", frame, x_home_px=5.0, y_home_px=5.0)
    assert result["frame_id"] == "f1"
    assert result["snapped"] is True
    # mm (50, 50) -> home px: 50/50*4 = 4.0 on both axes.
    assert result["x_home_px"] == pytest.approx(4.0)
    assert result["y_home_px"] == pytest.approx(4.0)
    # sqrt(2) ~= 1.41421, rounded to 1 decimal by the handler like x/y_home_px.
    assert result["distance_px"] == pytest.approx(1.4, abs=1e-9)


def test_snap_wall_corner_no_walls_echoes_point_unchanged() -> None:
    from custom_components.anyvac.services import _snap_wall_corner

    mask = np.zeros((5, 5), dtype=bool)
    frame = {"wall_mask": mask, "cell_mm": 50, "scale": 4, "origin_mm": (0.0, 0.0)}
    result = _snap_wall_corner("f1", frame, x_home_px=7.5, y_home_px=3.2)
    assert result == {
        "frame_id": "f1",
        "snapped": False,
        "x_home_px": 7.5,
        "y_home_px": 3.2,
    }


def test_snap_wall_corner_defaults_scale_and_cell_mm_when_missing() -> None:
    from custom_components.anyvac.services import _snap_wall_corner

    mask = np.zeros((5, 5), dtype=bool)
    mask[0, 0] = True
    # No "cell_mm"/"scale" keys at all -> falls back to 50mm / HOME_PX_SCALE(4),
    # i.e. must behave identically to the explicit-keys test above.
    frame = {"wall_mask": mask, "origin_mm": (0.0, 0.0)}
    result = _snap_wall_corner("f1", frame, x_home_px=5.0, y_home_px=5.0)
    assert result["snapped"] is True
    assert result["x_home_px"] == pytest.approx(4.0)
    assert result["y_home_px"] == pytest.approx(4.0)
